### ISSUE TITLE
Please configure the Doctrine extensions using the section 'doctrine:'

### ISSUE THREAD

**Issue by Sophyx** [Kdyby/Console#60]
Ahoj,

chcel by som sa opytat, popr. mat jeden dotaz.
Webova aplikacia mi funguje skvele, bez najmensich problemov, pracujem s DB, insertujem, updatujem, selectujem. Ale akonahle idem pustit hocijaky command 

`php www/index.php` 

tak mi vybehne tato chyba

Please configure the Doctrine extensions using the section 'doctrine:'

Mam ju ale registrovanu:

```
extensions:
  doctrine: Kdyby\Doctrine\DI\OrmExtension


doctrine:
  metadata:
    App: %appDir%/model/entities # temporary /entites cause Nette default models
```

Je mozne, ze to ma cache ?
